name: CI

on:
  push:
    branches:
      - main
      - georgedev/**
      - develop
      - feature/**

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Install pnpm
      - name: Install pnpm
        run: npm install -g pnpm

      # 3. Install dependencies
      - name: Install dependencies
        run: pnpm install

      # 4. Copy .env.example files recursively
      - name: Copy .env.example files
        shell: bash
        run: find . -type f -name ".env.example" -exec sh -c 'cp "$1" "${1%.*}"' _ {} \;

      # 5. Type check
      - name: Type Check
        run: pnpm typecheck

      # 6. Lint (Link check)
      - name: Lint Check
        run: pnpm lint
